version: '3'

volumes:
  conf:


services:
  redis:
    image: "redislabs/redismod:latest"
    ports:
      - "6379:6379"
  insight:
    image: "redislabs/redisinsight:latest"
    depends_on:
      - redis
    ports:
      - "8088:8088"
    environment:
        - RIPORT=8088
  backend:
    image: "maguec/microservices-saga-backend"
    links:
      - "redis:redis"
    depends_on:
      - redis
    volumes:
      - "./conf:/conf:ro"
  frontend:
    image: "maguec/microservices-saga-frontend"
    links:
      - "redis:redis"
    ports:
      - "5010:5010"
    volumes:
      - "./conf:/conf:ro"
    environment:
        - APP_CONF=/conf/config.yml
